---

- name: Manage organizations
  awx.awx.organization:
    controller_host: "{{ awx_url }}"
    validate_certs: "{{ awx_validate_certs }}"
    controller_username: "{{ awx_user if awx_token is undefined else omit }}"
    controller_password: "{{ awx_pass if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"

    name: "{{ organization.name }}"
    state: "{{ organization.state | default(omit) }}"
    description: "{{ organization.description | default(omit) }}"
    galaxy_credentials: "{{ organization.galaxy_credentials | default(omit) }}"

  become: false
  loop: "{{ awx_organizations }}"
  loop_control:
    loop_var: organization
  when: awx_manage_organizations | bool
