---

- name: Define fact awx_resources
  ansible.builtin.set_fact:
    awx_resources: "{{ awx_resources_all['awx_resources'][org_short] }}"

- name: Manage inventory for {{ org }}
  ansible.builtin.include_tasks: resources/inventory.yml
  when: awx_manage_inventories | bool and awx_resources['inventories'] is defined

- name: Manage users for {{ org }}
  ansible.builtin.include_tasks: resources/user.yml
  when: awx_manage_users | bool and awx_resources['users'] is defined

- name: Manage teams for {{ org }}
  ansible.builtin.include_tasks: resources/team.yml
  when: awx_manage_teams | bool and awx_resources['teams'] is defined

- name: Manage credentials for {{ org }}
  ansible.builtin.include_tasks: resources/credential.yml
  when: awx_manage_credentials | bool and awx_resources['credentials'] is defined

- name: Manage groups for {{ org }}
  ansible.builtin.include_tasks: resources/group.yml
  when: awx_manage_groups | bool and awx_resources['hostgroups'] is defined

- name: Manage hosts for {{ org }}
  ansible.builtin.include_tasks: resources/host.yml
  when: awx_manage_hosts | bool and awx_resources['hosts'] is defined

- name: Manage projects for {{ org }}
  ansible.builtin.include_tasks: resources/project.yml
  when: awx_manage_projects | bool and awx_resources['projects'] is defined

- name: Manage job_templates for {{ org }}
  ansible.builtin.include_tasks: resources/job_template.yml
  when: awx_manage_job_templates | bool and awx_resources['job_templates'] is defined

- name: Manage schedules for {{ org }}
  ansible.builtin.include_tasks: resources/schedule.yml
  when: awx_manage_schedules | bool and awx_resources['schedules'] is defined

- name: Manage roles for {{ org }}
  ansible.builtin.include_tasks: resources/roles.yml
  when: awx_manage_roles | bool
