---

- name: Manage credentials
  awx.awx.credential:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_user if awx_token is undefined else omit }}"
    controller_password: "{{ awx_pass if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_validate_certs }}"

    name: "{{ credential.name }}"
    description: "{{ credential.description | default(omit) }}"
    organization: "{{ organization.name | default(omit) }}"
    credential_type: "{{ credential.credential_type | default('Machine') }}"
    user: "{{ credential.user | default(omit) }}"
    update_secrets: "{{ credential.update_secrets | default(omit) }}"
    inputs: "{{ credential.inputs | default(omit) }}"

  become: false
  loop: "{{ awx_resources['credentials'] }}"
  loop_control:
    loop_var: credential
    label: "{{ credential.name }}"
