---

- name: Manage groups
  awx.awx.group:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_user }}"
    controller_password: "{{ awx_pass }}"
    validate_certs: "{{ awx_validate_certs }}"

    name: "{{ group.name }}"
    state: "{{ group.state|default('present') }}"
    inventory: "{{ group.inventory }}"
    description: "{{ group.description | default(omit) }}"
    variables: "{{ group.variables | default({}) }}"

  become: false
  loop: "{{ awx_resources['groups'] }}"
  loop_control:
    loop_var: group
    label: "{{ group.name }}"
