---

- name: Manage inventory
  awx.awx.inventory:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_user if awx_token is undefined else omit }}"
    controller_password: "{{ awx_pass if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_validate_certs }}"

    name: "{{ inventory.name }}"
    description: "{{ inventory.description | default(inventory.name) }}"
    organization: "{{ organization.name }}"
  become: false
  loop: "{{ awx_resources['inventories'] }}"
  loop_control:
    loop_var: inventory
    label: "{{ inventory.name }}"
