---

- name: Manage inventory
  awx.awx.inventory:
    controller_host:       "{{ awx_url }}"
    controller_username:   "{{ awx_user }}"
    controller_password:   "{{ awx_pass }}"
    validate_certs:        "{{ awx_validate_certs }}"

    name: "{{ inventory.name }}"
    description: "{{ inventory.description | default(inventory.name) }}"
    organization: "{{ organization.name }}"
  become: false
  loop: "{{ awx_resources['inventories'] }}"
  loop_control:
    loop_var: inventory
    label: "{{ inventory.name }}"
