---
- name: Manage team
  awx.awx.team:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_user if awx_token is undefined else omit }}"
    controller_password: "{{ awx_pass if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_validate_certs }}"

    name: "{{ team.name }}"
    description: "{{ team.description | default(team.name) }}"
    organization: "{{ organization.name }}"
  become: false
  loop: "{{ awx_resources['teams'] }}"
  loop_control:
    loop_var: team
    label: "{{ team.name }}"
